# This is a basic workflow to help you get started with Actions

name: Deploy Virtual Machine

# Controls when the action will run. 
on:
  workflow_dispatch:
  inputs:
  resourceGroupName:
  description: Resource Group Name
  required: true

jobs:
  deploy-virtual-machine:
    
    runs-on:ubuntu-latest
    steps:
       -uses: actions/checkout@v2
        -name: Run a one-line script
         run: echo Hello, ${{ github.event.inputs.resourceGroupName }}

